### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by linakherchi** [janettetinoco/pinspo#5]
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

**Comment by linakherchi** [comment]
Thanks, Jannette ! 

No nested routes please. (Boards show & index) 

Make sure to have a wild card in both board follows and user follows DELETE verb.

Also, please arrange the display of routes according to the checklist above.

Thanks !

**Comment by linakherchi** [comment]
Thanks, Jannette ! 

You will need to change the description of user_follows.

Otherwise, all the rest looks good to me !

**Comment by janettetinoco** [comment]
Hi Lina, 
Copy and Paste got me, sorry.

Thank you!
