### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by linakherchi** [janettetinoco/pinspo#6]
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by linakherchi** [comment]
Thanks, Jannette ! 

Regarding `/boards/:boardId`, did you mean having PinIndex under that route?

**Comment by janettetinoco** [comment]
Hi Lina,
Yes, sorry that's what I meant. Thank you!
