### ISSUE TITLE
Boards MVP

### ISSUE THREAD

**Issue by linakherchi** [janettetinoco/pinspo#8]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by linakherchi** [comment]
+ Remove the blue outline on input click when I want to create/edit a new board + on the submit buttons
+ The + to create a new board needs to be centered 
+ BONUS if you are able to close the dropdown to create the board when a click happens outside of that area 

Great job !

**Comment by janettetinoco** [comment]
ok fixed,  thought the blue outline was just my browser.
